// 📖 Conteúdo do "Livro da Lua" — lista completa de comandos do Falta Lua.
// Cada entrada vira uma página do codex e também é documentada no README.

const CATEGORIAS = {
  diversao: { nome: '🎲 Diversão', cor: 0xC9B8F2, emoji: '🎲' },
  social: { nome: '💞 Social', cor: 0xE0C3F7, emoji: '💞' },
  util: { nome: '🛠️ Utilidades', cor: 0xB9A7E6, emoji: '🛠️' },
  organizacao: { nome: '📚 Organização', cor: 0xA895E0, emoji: '📚' },
  admin: { nome: '🛡️ Administração', cor: 0x8E7BD6, emoji: '🛡️' },
};

// prefix: nome do comando por prefixo ($)
const COMANDOS = [
  {
    nome: 'dado',
    categoria: 'diversao',
    emoji: '🎲',
    descricao: 'Rola dados no formato NdM, com modificadores. Ex: 2d6+3, 4d8-1.',
    uso: '$dado 2d6+3',
    exemplo: 'Rola 1d20 e mostra cada valor + modificador.',
  },
  {
    nome: 'moeda',
    categoria: 'diversao',
    emoji: '🪙',
    descricao: 'Cara ou coroa, com animação de giro e botão para jogar de novo.',
    uso: '$moeda',
    exemplo: 'Sorteia Cara ou Coroa e permite repetir com um botão.',
  },
  {
    nome: 'roleta',
    categoria: 'diversao',
    emoji: '🎡',
    descricao: 'Sorteia uma opção entre várias separadas por vírgula.',
    uso: '$roleta pizza, sushi',
    exemplo: 'Escolhe uma das opções e destaca a vencedora.',
  },
  {
    nome: '8ball',
    categoria: 'diversao',
    emoji: '🔮',
    descricao: 'A bola mágica responde sua pergunta com mistério.',
    uso: '$8ball o bot gosta de mim?',
    exemplo: 'Respostas místicas aleatórias com botão para perguntar de novo.',
  },
  {
    nome: 'ship',
    categoria: 'diversao',
    emoji: '💞',
    descricao: 'Calcula a compatibilidade amorosa entre dois membros.',
    uso: '$ship @a @b',
    exemplo: 'Mostra uma barra de amor e uma mensagem temática.',
  },
  {
    nome: 'guerra',
    categoria: 'diversao',
    emoji: '⚔️',
    descricao: 'Mini guerra de cartas: você vs bot, melhor de 3 rodadas.',
    uso: '$guerra',
    exemplo: 'Cada rodada revela cartas e o botão avança para a próxima.',
  },
  {
    nome: 'roleta_russa',
    categoria: 'diversao',
    emoji: '🔫',
    descricao: 'Uma roleta russa de 6 câmaras. Você sobrevive?',
    uso: '$roleta_russa',
    exemplo: 'Sorteia a câmara e diz se você "sobreviveu".',
  },
  {
    nome: 'abraco',
    categoria: 'social',
    emoji: '🤗',
    descricao: 'Envia um abraço carinhoso para alguém (ou para você).',
    uso: '$abraco @alguem',
    exemplo: 'Menciona o usuário com uma mensagem fofa.',
  },
  {
    nome: 'cartasecreta',
    categoria: 'social',
    emoji: '✉️',
    descricao: 'Entrega uma carta anônima/misteriosa para um membro.',
    uso: '$cartasecreta @a oi',
    exemplo: 'Envia a mensagem como uma carta selada no privado do alvo.',
  },
  {
    nome: 'social',
    categoria: 'social',
    emoji: '👤',
    descricao: 'Mostra um cartão de perfil do usuário, com botões de ações.',
    uso: '$social @alguem',
    exemplo: 'Cartão com avatar, tag, cargo e botões de interação.',
  },
  {
    nome: 'avatar',
    categoria: 'util',
    emoji: '🖼️',
    descricao: 'Mostra o avatar de um usuário em tamanho grande.',
    uso: '$avatar @alguem',
    exemplo: 'Botões para baixar e trocar entre avatar e avatar do servidor.',
  },
  {
    nome: 'membros',
    categoria: 'util',
    emoji: '👥',
    descricao: 'Conta membros, bots e humanos do servidor.',
    uso: '$membros',
    exemplo: 'Embed com contadores e botão de atualizar.',
  },
  {
    nome: 'status',
    categoria: 'util',
    emoji: '📡',
    descricao: 'Mostra o status da bot (latência, servidores, uptime).',
    uso: '$status',
    exemplo: 'Latência da API e do bot em ms.',
  },
  {
    nome: 'votar',
    categoria: 'util',
    emoji: '🗳️',
    descricao: 'Cria uma enquete rápida com botões de opções.',
    uso: '$votar sua pergunta? opcao1, opcao2, opcao3',
    exemplo: 'Cada opção vira um botão; clicar conta o voto.',
  },
  {
    nome: 'sobre',
    alias: ['mila', 'faltalua'],
    categoria: 'util',
    emoji: '🌙',
    descricao: 'Sobre a Falta Lua — quem ela é e o que faz.',
    uso: '$sobre  •  $mila  •  $faltalua',
    exemplo: 'Cartão de apresentação da bot.',
  },
  {
    nome: 'logs',
    categoria: 'admin',
    emoji: '📜',
    descricao: 'Mostra os logs registrados pela bot, com filtro por pessoa.',
    uso: '$logs @alguem',
    exemplo: 'Veja o histórico organizado ou filtre por um usuário específico.',
  },
  {
    nome: 'lembrete',
    categoria: 'util',
    emoji: '⏰',
    descricao: 'Cria, lista ou cancela lembretes agendados.',
    uso: '$lembrete 10m beber água',
    exemplo: 'A bot te avisa no canal no tempo certo.',
  },
  {
    nome: 'configurar',
    categoria: 'organizacao',
    emoji: '⚙️',
    descricao: 'Define onde a bot fala e organiza canais de anúncio (requer Gerir Servidor).',
    uso: '$configurar ver | permitir | proibir | anuncio',
    exemplo: 'Controla canais permitidos/proibidos e roteamento de anúncios.',
  },
  {
    nome: 'anuncio',
    categoria: 'organizacao',
    emoji: '📣',
    descricao: 'Envia anúncio classificado no canal do tipo (requer Gerir Servidor).',
    uso: '$anuncio evento Sexta tem evento!',
    exemplo: 'Tipos: geral, evento, regra, atualizacao, aviso.',
  },
  {
    nome: 'organizar',
    categoria: 'organizacao',
    emoji: '🗂️',
    descricao: 'Painel de organização do servidor e roteamento de anúncios.',
    uso: '$organizar',
    exemplo: 'Visão geral de categorias e canais configurados.',
  },
  {
    nome: 'codex',
    categoria: 'organizacao',
    emoji: '📖',
    descricao: 'Este livro: lista todos os comandos, página a página.',
    uso: '$codex  •  $codex roleta',
    exemplo: 'Navegue com botões, menu de pular e busca por nome.',
  },
  {
    nome: 'limpar',
    categoria: 'admin',
    emoji: '🧹',
    descricao: 'Apaga mensagens recentes do canal (requer Gerenciar Mensagens).',
    uso: '$limpar 10',
    exemplo: 'Remove até N mensagens com confirmação.',
  },
  {
    nome: 'lentidao',
    categoria: 'admin',
    emoji: '🐌',
    descricao: 'Define o modo lento (slowmode) do canal (requer Gerenciar Canais).',
    uso: '$lentidao 5',
    exemplo: 'Define o intervalo mínimo entre mensagens.',
  },
  {
    nome: 'aviso',
    categoria: 'admin',
    emoji: '📢',
    descricao: 'Atalho de anúncio geral em qualquer canal (requer Gerir Servidor).',
    uso: '$aviso sua mensagem aqui',
    exemplo: 'Envia aviso destacado no canal atual.',
  },
  {
    nome: 'seguranca',
    categoria: 'admin',
    emoji: '🛡️',
    descricao: 'Dicas de segurança para o servidor e a bot.',
    uso: '$seguranca',
    exemplo: 'Lista práticas de proteção.',
  },
  {
    nome: 'ping',
    categoria: 'util',
    emoji: '🏓',
    descricao: 'Responde Pong! para testar se a bot está viva.',
    uso: '$ping',
    exemplo: 'Resposta rápida de teste.',
  },
];

const TOTAL = COMANDOS.length;

module.exports = { CATEGORIAS, COMANDOS, TOTAL };